#!/usr/bin/env bash
echo -e '### Starting Kali container ###'
podman start Kali
echo -e '### Attaching to session ###'
echo -e 'To connect another window or connect manually you can log in over SSH'
podman attach Kali